### PR TITLE
Added ability to deploy OST to cloud foundry

### PR DESCRIPTION
**Pull request by haleystorm**
* Created cloud foundry manifest
* Created new script for starting OST that works in cloud foundry
* Modified ant build to package OST distribution with start script in bin folder instead of folder called scripts because cloud foundry could not detect script otherwise.
* Updated readme

### CODE REVIEW

**Comment by dlutz2** [comment]
Looks good to me and Travis says OK. Travis and I can't test the CF deployment so if it works for you must be good.
In 3.0, I will move all scripts to /bin (unless CF will complain about other stuff there), no reason to have two dirs.

**Comment by haleystorm** [comment]
CF complains if the other scripts are in /bin. However, CF doesn't care if both the /bin and /scripts exist as long as /bin only contains the one runnable.

Should I remove release-pcf target from the ant build and just create both /bin and /scripts? It seems weird to have both. Thoughts?

**Comment by haleystorm** [comment]
I didn't test the CF deployment with the full gazetteer. Turns out that the resulting zip file is too large to push. CF has a 1G limit on app package sizes. Will need to explore running with an external solr instance.

**Comment by dsmiley** [comment]
Couldn't the data be loaded separately somehow?  Disclaimer: I know nothing of CF but have been learning Docker.

**Comment by dlutz2** [comment]
Having a separate ant target for the CF build is OK. If CF is picky about other stuff in bin best keep both /bin and /scripts.
Haven't tried the separate Solr instance for a while. I know the throughput drops sharply. Let me know how it goes.

**Comment by haleystorm** [comment]
Yay. I have a working Solr instance and OpenSextant in CF can reach it. Going to open another pull request. I'm hoping the throughput won't be an issue but will keep an eye on it. Thanks.

**Pull request merged**
